### ISSUE TITLE
QuestionLinearScale is not printing answer comment field 

### ISSUE THREAD

**Issue by rbyh** [goemeritus/edsl#1]
An answer "comment" field is automatically captured for each agent response. See the common prompt:
```
Return a valid JSON formatted like this, selecting only the number of the option: 
{"answer": <put answer code here>, "comment": "<put explanation here>"}

```
We can print the answer comment for other question types eg multiple choice but not for linear scale:
<img width="1078" alt="image" src="https://github.com/goemeritus/edsl/assets/50664588/b14f659e-312a-4716-b49e-56d6a4298129">

We do see the comment exists in the db:
<img width="931" alt="image" src="https://github.com/goemeritus/edsl/assets/50664588/d953c03f-70fa-478c-b86e-c8acd37e8832">

**Comment by apostolosfilippas** [comment]
@rbyh should be fixed in 33a442b
