### ISSUE TITLE
General cleanup and re-factor ideas

### ISSUE THREAD

**Issue by johnjosephhorton** [goemeritus/edsl#12]
- [x] Create a 'Prompt' class and allow questions to have model-specific prompts
- [x] Remove HTML / form-based display from Questions as largely unused 
- [x] Remove the notion of survey and question UUIDs
- [x] Move "docx" method to edsl[extra]
- [x] Move all plotting / output methods to edsl[extra]
- [x] Refactor "type" in Question to "question_type" as type is a reserved keyword in python, which causes trouble 
- [ ] ??

**Comment by apostolosfilippas** [comment]
- [ ] Would really love all base objects to have an "example" method (create an example for this class) 
- [ ] Maybe thy should also have a "methods" method (show useful methods and short descr)
- [ ] move prompt creation out of Agent
- [ ] Interview orchestration needs refactoring. This will take some work. 
- [ ] Threading works on personal computers but won't on cloud. Need to move towards using async

**Comment by johnjosephhorton** [comment]
great stuff

**Comment by johnjosephhorton** [comment]
Closing because I think we got them all! The only one we didn't really do was integrated help. I think the way to do this will be with a meta class, like I did w/ LanguageModel. But let's discuss before we re-factor.
