### ISSUE TITLE
Re-factor Questions

### ISSUE THREAD

**Issue by johnjosephhorton** [goemeritus/edsl#17]
- [x] Refactor Question.py so __init__ is not called 
- [x] Write custom validators for answers & questions - start with MC & free text 
- [x] Move prompt creation out of Question.py to separate classes ; refactor interviewing accordingly 
- [x] Turn over system prompt and fine-grained prompt control to use
- [x] Use Metaclass for the question registry

**Comment by apostolosfilippas** [comment]
Some more things @johnjosephhorton 

- [ ] It'd be nice to add integration tests for each of the questions that we support.
- [ ] QuestionFunctional and Question.__add__ need work
- [ ] We should be always allowing both {'answer': 1} and {'answer':'1'} to go through
- [ ] Allowing non-responses at the question level feels kind of weird atm. Either allow it and demand all questions to have it, or do it at some other level (survey?)
- [ ] The way i've implemented it, 'comment' is always optional, in that answer validation will go through even if it is missing. We should get consistent here.

Nice to haves:
- [ ] descriptors could be made DRYer/better
- [ ] answer validation could be made DRYer/better

**Comment by johnjosephhorton** [comment]
I'm going to close this issue and create a new consolidated issue, as most have been addressed.
