### ISSUE TITLE
to_csv only saves the second model's responses

### ISSUE THREAD

**Issue by benjamin-manning** [goemeritus/edsl#4]
When i do response.to_csv('xyz.csv') (response being a class Results object I think)
It only saves the queries from the model that is run second:
e.g., in this case the csv only has the responses from 3.5
```
responses = q.by(scenarios).by(m4).by(m35).run()
# this case it only has the responsess from 4
responses = q.by(scenarios).by(m35).by(m4).run()
```

**Comment by johnjosephhorton** [comment]
@rbyh First step would be to make sure the results are "there" in the results - could be a bug higher up than at the export layer

**Comment by johnjosephhorton** [comment]
Can you create a code example as complete .py file that demonstrates the
failure - have it throw an exception for the unexpected behavior and I’ll
use as a test to develop a fix against

**Comment by johnjosephhorton** [comment]
This is actually a desired feature - there should only one "by" of each type, as they are indicating full cartesian products and you can't cross two things. As a convenience, we do allow bys for items that can be combined (as in the case of scenarios or agents). For models, there is no notion of combining them, so the code just takes the first one. This might be surprising, so as a 'fix' I'm going to just print a warning to use the other method @rbyh  proposed.
